/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddQuestion: typeof import('./src/components/AddQuestion/AddQuestion.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CodeIcon: typeof import('./src/components/icons/CodeIcon.vue')['default']
    copy: typeof import('./src/components/MdEditor copy.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor.vue')['default']
    Result: typeof import('./src/components/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAffix: typeof import('tdesign-vue-next')['Affix']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TFrom: typeof import('tdesign-vue-next')['From']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TMen: typeof import('tdesign-vue-next')['Men']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSub: typeof import('tdesign-vue-next')['Sub']
    TSubm: typeof import('tdesign-vue-next')['Subm']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTagInput: typeof import('tdesign-vue-next')['TagInput']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
